
from flask import Flask, render_template, request
from flask_socketio import SocketIO
import cv2
from ultralytics import YOLO
import pyttsx3
import time
import threading
import random
from datetime import datetime
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

app = Flask(__name__)
socketio = SocketIO(app)

model = YOLO("yolov8n.pt")
print("Model loaded!")

tts = pyttsx3.init()
tts.setProperty('rate', 150)

last_detection = 0
last_email = 0
detection_gap =5
email_gap = 30


HAZARDS = [
    "bicycle", "motorcycle", "car", "truck", "bus",
    "dog", "cat", "cow", "horse",
    "bench", "chair", "suitcase", "backpack", "umbrella"
]


VOICE_MESSAGES = {
    "dog": "Warning! Street dog ahead. Please be careful.",
    "cow": "Warning! Cow blocking the footpath.",
    "cat": "Warning! Animal on footpath ahead.",
    "motorcycle": "Warning! Motorcycle blocking footpath. Please go around.",
    "bicycle": "Warning! Bicycle on footpath ahead.",
    "car": "Warning! Vehicle blocking footpath.",
    "truck": "Warning! Large vehicle blocking path.",
    "bus": "Warning! Bus blocking footpath ahead.",
    "bench": "Warning! Obstruction on footpath ahead.",
    "chair": "Warning! Chair blocking path.",
    "suitcase": "Warning! Luggage blocking footpath.",
    "backpack": "Warning! Object on footpath ahead.",
    "umbrella": "Warning! Obstruction detected ahead.",
}

BASE_LAT = 12.9716
BASE_LNG = 77.5946
REAL_LAT = 12.9716
REAL_LNG = 77.5946

SENDER = "sidewalkhackathon@gmail.com"
PASSWORD = "oeho tobw kvnc pbsq"
RECEIVER = "sidewalkhackathon@gmail.com"
email_count = 0


def speak(label):
    msg = VOICE_MESSAGES.get(label, f"Warning! {label} blocking footpath. Please be careful.")
    def say():
        try:
            import pyttsx3
            e = pyttsx3.init()
            e.setProperty('rate', 150)
            e.setProperty('volume', 1.0)
            e.say(msg)
            e.runAndWait()
            del e
        except Exception as ex:
            print(f"Voice alert: {ex}")
            try:
                import subprocess
                subprocess.run(['powershell', '-Command',
                    f'Add-Type -AssemblyName System.Speech; '
                    f'$s = New-Object System.Speech.Synthesis.SpeechSynthesizer; '
                    f'$s.Speak("{msg}")'],
                    capture_output=True)
            except:
                pass
    t = threading.Thread(target=say)
    t.daemon = True
    t.start()


def send_email(label, confidence, lat, lng):
    global email_count
    email_count += 1
    msg = MIMEMultipart()
    msg['From'] = SENDER
    msg['To'] = RECEIVER
    msg['Subject'] = f"SafeWalk Alert #{email_count} - {label} on footpath"
    body = f"""
SafeWalk Hazard Report #{email_count}

Hazard      : {label.upper()}
Confidence  : {confidence:.0%}
Location    : {lat:.6f}, {lng:.6f}
Area        : Near {lat:.4f}, {lng:.4f} - Bengaluru
Time        : {datetime.now().strftime("%I:%M:%S %p, %d %B %Y")}

Please inspect and clear this footpath hazard
within 48 hours as per BBMP guidelines.

Auto-generated by SafeWalk
WitchHunt Hackathon 2026 
    """
    msg.attach(MIMEText(body, 'plain'))
    try:
        s = smtplib.SMTP('smtp.gmail.com', 587)
        s.starttls()
        s.login(SENDER, PASSWORD)
        s.send_message(msg)
        s.quit()
        print(f"Email #{email_count} sent!")
        socketio.emit('complaint_sent', {
            'count': email_count,
            'label': label,
            'time': datetime.now().strftime("%I:%M:%S %p")
        })
    except Exception as e:
        print(f"Email failed: {e}")


def push_to_map(label, confidence, lat, lng):
    socketio.emit('new_hazard', {
        'label': label,
        'confidence': f"{confidence:.0%}",
        'lat': lat,
        'lng': lng,
        'time': datetime.now().strftime("%I:%M:%S %p")
    })
    print(f"Pin: {label} at {lat:.4f}, {lng:.4f}")


def start_camera():
    global last_detection, last_email
    cam = cv2.VideoCapture(0)
    print("Camera on!")

    while True:
        ok, frame = cam.read()
        if not ok:
            break

        detections = model(frame, verbose=False)

        for result in detections:
            for box in result.boxes:
                conf = float(box.conf[0])
                if conf < 0.5:
                    continue

                label = model.names[int(box.cls[0])]
                x1, y1, x2, y2 = map(int, box.xyxy[0])

                if label in HAZARDS:
                    color = (0, 0, 255)
                    now = time.time()
                    if now - last_detection > detection_gap:
                        last_detection = now
                        lat = REAL_LAT + random.uniform(-0.0002, 0.0002)
                        lng = REAL_LNG + random.uniform(-0.0002, 0.0002)
                        push_to_map(label, conf, lat, lng)
                        speak(label)
                        if now - last_email > email_gap:
                            last_email = now
                            t = threading.Thread(
                                target=send_email,
                                args=(label, conf, lat, lng)
                            )
                            t.daemon = True
                            t.start()
                else:
                    color = (0, 255, 0)

                cv2.rectangle(frame, (x1, y1), (x2, y2), color, 2)
                cv2.putText(frame, f"{label} {conf:.0%}", (x1, y1 - 10),
                           cv2.FONT_HERSHEY_SIMPLEX, 0.6, color, 2)

        cv2.putText(frame, "SafeWalk - LIVE", (10, 30),
                   cv2.FONT_HERSHEY_SIMPLEX, 0.8, (20, 255, 236), 2)
        cv2.namedWindow("SafeWalk Camera", cv2.WINDOW_AUTOSIZE)
        cv2.setWindowProperty("SafeWalk Camera", cv2.WND_PROP_TOPMOST, 1)
        cv2.moveWindow("SafeWalk Camera", 100, 100)
        cv2.imshow("SafeWalk Camera", frame)

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    cam.release()
    cv2.destroyAllWindows()


@app.route('/')
def home():
    return render_template('map.html')


@app.route('/simulate')
def simulate():
    hazards = ["motorcycle", "dog", "cow", "bicycle", "car"]
    label = random.choice(hazards)
    conf = random.uniform(0.75, 0.98)
    lat = REAL_LAT + random.uniform(-0.0002, 0.0002)
    lng = REAL_LNG + random.uniform(-0.0002, 0.0002)
    push_to_map(label, conf, lat, lng)
    return "ok"


@app.route('/update_location')
def update_location():
    global REAL_LAT, REAL_LNG
    REAL_LAT = float(request.args.get('lat', BASE_LAT))
    REAL_LNG = float(request.args.get('lng', BASE_LNG))
    print(f"Location: {REAL_LAT}, {REAL_LNG}")
    return "ok"


if __name__ == '__main__':
    cam_thread = threading.Thread(target=start_camera)
    cam_thread.daemon = True
    cam_thread.start()
    print("SafeWalk running at http://localhost:5000")
    socketio.run(app, debug=False, port=5000, allow_unsafe_werkzeug=True)